version: '3.5'

services:

  roach1:
   image: cockroachdb/cockroach
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure
   volumes:
     - roach1-data:/cockroach/cockroach-data
volumes:
  roach1-data:


